#!/bin/bash

main='/root/code/xujijingdu'

cd $main || exit 1

deploy() {
    clean
    mkdir -p public/{css,js,img}
    cp -a src/index.html public
    cp -a src/image/logo.png public/img
    cp -a src/image/background.jpeg public/img

    python -m http.server -d public 80
}

clean() {
    [ -d public ] || return 0
    rm -fr public
    mkdir public
}

"$@"
